### ISSUE TITLE
Automatic turn-by-turn instructions

### ISSUE THREAD

**Issue by Ramshandilya** [phunware/maas-mapping-ios-sdk#134]
Hi team,

I followed the MapScenarios sample and I found it super helpful in implementing turn-by-turn navigation.

One issue I had was that, in turn-by-turn routing, users will have to manually interact to get the next route instruction. Is it possible to do something like Google maps where the route instructions update automatically without any user interaction? Can the SDK watch for completion of an instruction and give a callback (where we can update to next instruction)?

Let me know if this is out of scope.

Thanks,
Ram

**Comment by ktu-phunware** [comment]
Hi Ram,
For route instructions to automatically update we need to set up your site to do indoor navigation.  In the app, you'll need register a PWManagedLocationManager, then create a route from start location to your destination .  When those steps are done, our mapping sdk will call the "func mapView(_ mapView: PWMapView!, didChange instruction: PWRouteInstruction!)" delegate when it detect a user's location is on the next segment of the route.  Please see OffRouteViewController.swift in the MapScenarios sample app for the full implementation.  Hope this answers your question.

Thanks,
Kent

**Comment by Ramshandilya** [comment]
Hi Kent,

I think that helps. I'll give it a try and get back if I face any issues. 
Thanks!

**Comment by ghost** [comment]
Hi @Ramshandilya,

Please close this issue if the answer provided by @ktu-phunware has solved your issue.

Thanks!
Troy
