### ISSUE TITLE
Code compiling Error in simulator and Devices  

### ISSUE THREAD

**Issue by MuraliNallusami** [phunware/maas-mapping-ios-sdk#66]
Got few errors in recent version Git update. Can you help in fixing. 

Error:
Use of undeclared type 'PWUserLocation'
Value of type 'PWMapView' has no member 'indoorUserLocation' 
Value of type 'PWMapView' has no member 'view'

**Comment by pdunshee-phunware** [comment]
Hey MuraliNallusami, happy to assist you with this. Could you please clarify which version of PWMapKit you are upgrading from, and which version you are upgrading to? This document might answer your questions as well: https://github.com/phunware/maas-mapping-ios-sdk/wiki/Upgrade-from-3.x.x-to-3.2.0

**Comment by ghost** [comment]
Closing stale issues - if this persists, please let us know by opening a new issue. Thanks!
