### ISSUE TITLE
PWMapping SDK - Load Building Dynamically

### ISSUE THREAD

**Issue by harishios** [phunware/maas-mapping-ios-sdk#83]
Hi Team,

Mapping SDK works good with the Static Building ID, but how to load the building dynamically when the user crosses the geofence of different buildings?

**Comment by peterwangxw** [comment]
Hi @harishios, you can use `– setBuilding:animated:onCompletion:` in `PWMapView` to dynamically switch the display building. There are two steps in this method: 1> to remove the existing building if possible. 2> add the new building on the map.

For your case, you should use PWBuilding to loading the building when detecting geofence crosses, then use `– setBuilding:animated:onCompletion:` to display the building after it's completed.

**Comment by harishios** [comment]
Hi @xwang-phunware Thanks for your quick response, yes I do understand that `– setBuilding:animated:onCompletion:` is used to load the building.

My concern is, is there anyway that Phunware SDK gives any callback like in which _**Building**_ user is inside. Eg: Through `PWGeoZone` class, is there any possibility to detect like if the user is inside any building.

**Comment by peterwangxw** [comment]
Hi @harishios, there isn't an out of box feature for that. But you can definitely do it by associating the _buildingId_ to a `PWGeoZone`(use the **code** field  etc) or putting the _buildingId_ as a metadata in the Geofence entry campaign, then you could get the corresponding _buildingId_ and start loading the building to display on the map when the geofence entry fires.

**Comment by harishios** [comment]
Thanks for the response @xwang-phunware.

1. Is there any particular way to get the callback when the geofence entry fires in iOS?
2. How to associate the _buildingId_ to a `PWGeoZone`(use the code field etc)?

Help is much appreciated.

**Comment by peterwangxw** [comment]
1. You can observe geofence entry notification via key `PWMEEnterGeoZoneNotificationKey`, and then get the `geofenceId` from the notification userInfo via `PWMEGeoZoneIdentifierKey`. 
2. I apologize the `code` field was removed from MaaS portal for a while, but you can use `tags` instead.

```
// Observe Geofence entry 
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(YOUR_METHOD) name:PWMEEnterGeoZoneNotificationKey object:nil]

// The method to load the building and render on map
- (void)YOUR_METHOD:(NSNotification *)notification {
    NSString *zoneId = notification.userInfo[PWMEGeoZoneIdentifierKey];
    PWMEGeozone *zone = [[PWEngagement geozones] filteredArrayUsingPredicate:[NSPredicate predicateWithFormat:@"identifier[c] == '%@'", zoneId]].firstObject;
    // Parse the buildingId from tags and then load and display the building on the map
    NSString *buildingId = ....;
    ....
}
```

**Comment by harishios** [comment]
Perfect. This helps a lot. In this case then there is not need to have the Meta data in campaign message?

**Comment by peterwangxw** [comment]
Yes, you don't need to put in campaign metatdata.

**Comment by harishios** [comment]
Thanks @xwang-phunware - Your solution to use `tags` is working perfectly fine.

One last query, Why I'm not getting the meta data which I passed in _Geo Entry Campaign_ in `notification` user info?

**Comment by peterwangxw** [comment]
Hi @harishios, the `metadata` does not come with notification userInfo, you should get it from message object. 
https://phunware.github.io/maas-engagement-ios-sdk/Classes/PWMEZoneMessage.html#//api/name/metaData

**Comment by harishios** [comment]
Hi @xwang-phunware - Perfect 👍 
`PWEngagement.messages()` gives me an empty array after the Geo Entry notification is fired. I'm doing right?

**Comment by peterwangxw** [comment]
Hi @harishios The meta data has to be added when you create geofence entry campaign like the attached screenshot, have you done that?

<img width="715" alt="create_entry_campaign" src="https://user-images.githubusercontent.com/1281268/49902688-3d942280-fe2a-11e8-8aca-30a85d456479.png">

**Comment by harishios** [comment]
Yes @xwang-phunware all these are done! 

Also the GeoFence Entry notifications are not consistent.

**Comment by peterwangxw** [comment]
Hi @harishios  Looks something unstable for Engagement SDK, please try to use the latest version. (If you still couldn't get it work, someone will help you if you post on https://github.com/phunware/maas-engagement-ios-sdk)

As you have already had it works with geofence `tags`, I think it's unnecessary for you to use notification any more(it's duplicated).
