### ISSUE TITLE
App crash on iOS when we goto Background and come back

### ISSUE THREAD

**Issue by harishios** [phunware/maas-mapping-ios-sdk#85]
Whenever I go to background and launch the application which contains the Phunware Mapping and Engagement SDK the application is terminated. 

Attached is the screenshot of Log which I'm getting. 
<img width="398" alt="crash" src="https://user-images.githubusercontent.com/18008999/52359027-10698800-2a07-11e9-98d7-98606ef396a1.png">

**Comment by pdunshee-phunware** [comment]
Thanks harishios, we're looking into it. Can you please let us know which project you're working on so we can move updates to the appropriate support channel, as well as which versions of the SDKs you are using?

**Comment by harishios** [comment]
I'm working on `PWMapKit`. PWMapKitVersion = 3.6.0

**Comment by pdunshee-phunware** [comment]
I meant which app project are you working on -- we have Slack channels for specific customers/partners we work with to provide a better support process.

Could you also please provide the other Phunware SDK versions you are using? PWLocation and PWCore should be included in your Podfile.lock, and you mentioned including PWEngagement in your project as well.

**Comment by harishios** [comment]
PWLocationVersion = 3.6.0, PWEngagementVersion = 3.4.2.

**Comment by pdunshee-phunware** [comment]
I'd recommend updating to the latest PWEngagement version (3.7.2 at time of writing), many bug fixes have gone in since 3.4.2 (specifically in 3.4.3 we fixed a crash when opening a broadcast notification from the background, which could be your issue). For further support, please reach us on our intercompany Slack channels or support@phunware.com

**Comment by harishios** [comment]
@pdunshee-phunware Thanks for your response. This issue is specific to PWMapKit as the crash is occurring even without integration of the PWEngagement.

**Comment by harishios** [comment]
@pdunshee-phunware: Thanks for the update. The issue is fixed once the latest PWEngagement SDK is updated. Thanks.
